package com.security.backend.utils;

import cn.hutool.core.util.StrUtil;
import cn.hutool.json.JSONUtil;
import com.security.backend.domain.result.Result;
import com.security.backend.enums.DeviceType;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.util.StreamUtils;

import java.io.IOException;
import java.math.BigDecimal;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.UnknownHostException;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.List;
import java.util.regex.Pattern;

/**
 * HttpServlet 工具类
 * 用于获取请求相关的各种信息及响应处理
 *
 * @author Generated by DeepSeek
 * @date 2026-06-24
 */
@Slf4j
public record HttpServletUtils(HttpServletRequest request, HttpServletResponse response) {

    // ==================== IP 正则表达式常量 ====================

    /**
     * IPv4 正则表达式
     */
    private static final Pattern IPV4_PATTERN = Pattern.compile(
            "^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
    );

    /**
     * IPv6 正则表达式
     */
    private static final Pattern IPV6_PATTERN = Pattern.compile(
            "^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$|" +
                    "^([0-9a-fA-F]{1,4}:){1,7}:$|" +
                    "^([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}$|" +
                    "^([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}$|" +
                    "^([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}$|" +
                    "^([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}$|" +
                    "^([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}$|" +
                    "^[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})$|" +
                    "^:((:[0-9a-fA-F]{1,4}){1,7}|:)$|" +
                    "^fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}$|" +
                    "^::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])$|" +
                    "^([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])$"
    );

    /**
     * 响应内容类型：JSON。
     */
    public static final String CONTENT_TYPE = "application/json";

    /**
     * 字符集编码：UTF-8。
     */
    public static final String CHARSET = "utf-8";

    /**
     * 请求体最大读取大小（10MB）
     */
    private static final int MAX_REQUEST_BODY_SIZE = 10 * 1024 * 1024;

    // ==================== 请求头常量 ====================

    /**
     * User-Agent 请求头
     */
    private static final String HEADER_USER_AGENT = "User-Agent";

    /**
     * X-Forwarded-For 请求头（用于获取真实客户端 IP）
     */
    private static final String HEADER_X_FORWARDED_FOR = "X-Forwarded-For";

    /**
     * Proxy-Client-IP 请求头
     */
    private static final String HEADER_PROXY_CLIENT_IP = "Proxy-Client-IP";

    /**
     * WL-Proxy-Client-IP 请求头（WebLogic）
     */
    private static final String HEADER_WL_PROXY_CLIENT_IP = "WL-Proxy-Client-IP";

    /**
     * HTTP_CLIENT_IP 请求头
     */
    private static final String HEADER_HTTP_CLIENT_IP = "HTTP_CLIENT_IP";

    /**
     * HTTP_X_FORWARDED_FOR 请求头
     */
    private static final String HEADER_HTTP_X_FORWARDED_FOR = "HTTP_X_FORWARDED_FOR";

    /**
     * X-Device-Id 请求头（设备 ID）
     */
    private static final String HEADER_X_DEVICE_ID = "X-Device-Id";

    /**
     * Device-Id 请求头（设备 ID）
     */
    private static final String HEADER_DEVICE_ID = "Device-Id";

    /**
     * X-Device-Type 请求头（设备类型）
     */
    private static final String HEADER_X_DEVICE_TYPE = "X-Device-Type";

    /**
     * 所有需要检查的代理 IP 请求头数组
     */
    private static final String[] PROXY_IP_HEADERS = {
            HEADER_X_FORWARDED_FOR,
            HEADER_PROXY_CLIENT_IP,
            HEADER_WL_PROXY_CLIENT_IP,
            HEADER_HTTP_CLIENT_IP,
            HEADER_HTTP_X_FORWARDED_FOR
    };

    // ==================== User-Agent 匹配关键字常量 ====================

    /**
     * 移动设备关键字
     */
    private static final String[] UA_MOBILE_KEYWORDS = {
            "mobile", "android", "iphone", "ipod", "windows phone", "blackberry"
    };

    /**
     * 平板设备关键字
     */
    private static final String[] UA_TABLET_KEYWORDS = {
            "ipad", "tablet"
    };

    /**
     * PC 设备关键字
     */
    private static final String[] UA_PC_KEYWORDS = {
            "windows", "macintosh", "linux", "x11"
    };

    // ==================== User-Agent 校验常量 ====================

    /**
     * User-Agent 最小长度
     */
    private static final int UA_MIN_LENGTH = 10;

    /**
     * User-Agent 最大长度
     */
    private static final int UA_MAX_LENGTH = 512;

    /**
     * User-Agent 黑名单关键字
     */
    private static final List<String> UA_BLACKLIST_KEYWORDS = Arrays.asList(
            "curl", "wget", "python-requests", "httpclient", "okhttp",
            "java", "go-http-client", "perl", "ruby", "nmap", "sqlmap",
            "nikto", "nessus", "acunetix", "burpsuite", "zap",
            "headless", "phantomjs", "selenium", "puppeteer",
            "scrapy", "aiohttp", "httpx", "axios", "fetch"
    );

    /**
     * 搜索引擎爬虫关键字
     */
    private static final List<String> UA_SEARCH_ENGINE_KEYWORDS = Arrays.asList(
            "googlebot", "baiduspider", "bingbot", "yandexbot",
            "slurp", "duckduckbot", "facebookexternalhit", "twitterbot",
            "spider", "crawler", "bot"
    );

    // ==================== 其他常量 ====================

    /**
     * IP 地址分隔符（X-Forwarded-For 中多个 IP 的分隔符）
     */
    private static final String IP_SEPARATOR = ",";

    /**
     * 未知标识（用于 IP 头中的 unknown 值）
     */
    private static final String UNKNOWN_IP = "unknown";

    /**
     * 默认的未知值
     */
    private static final String DEFAULT_UNKNOWN = "Unknown";

    /**
     * 空字符串
     */
    private static final String EMPTY_STRING = "";

    // ==================== 构造器 ====================

    /**
     * 构造器，接收 HttpServletRequest 对象
     *
     * @param request HttpServletRequest 对象
     */
    public HttpServletUtils(HttpServletRequest request) {
        this(request, null);
    }

    /**
     * 构造器，接收 HttpServletResponse 对象
     *
     * @param response HttpServletResponse 对象
     */
    public HttpServletUtils(HttpServletResponse response) {
        this(null, response);
    }

    // ==================== 1. 获取 IPv4 地址 ====================

    /**
     * 获取客户端的 IPv4 地址
     * 优先从 X-Forwarded-For、Proxy-Client-IP、WL-Proxy-Client-IP 头中获取
     *
     * @return IPv4 地址，如果获取不到则返回 null
     */
    public String getIpv4() {
        String ip = getClientIp();
        if (ip != null && IPV4_PATTERN.matcher(ip).matches()) {
            return ip;
        }
        return null;
    }

    // ==================== 2. 获取 IPv6 地址 ====================

    /**
     * 获取客户端的 IPv6 地址
     * 优先从 X-Forwarded-For、Proxy-Client-IP、WL-Proxy-Client-IP 头中获取
     *
     * @return IPv6 地址，如果获取不到则返回 null
     */
    public String getIpv6() {
        String ip = getClientIp();
        if (ip != null && IPV6_PATTERN.matcher(ip).matches()) {
            return ip;
        }
        return null;
    }

    // ==================== 3. 获取设备类型 (deviceType) ====================

    /**
     * 获取设备类型
     * 根据 User-Agent 判断设备类型
     *
     * @return 设备类型枚举
     */
    public DeviceType getDeviceType() {
        String userAgent = request.getHeader(HEADER_USER_AGENT);
        if (userAgent == null || userAgent.isEmpty()) {
            return DeviceType.UNKNOWN;
        }

        userAgent = userAgent.toLowerCase();

        // 判断是否为移动设备
        for (String keyword : UA_MOBILE_KEYWORDS) {
            if (userAgent.contains(keyword)) {
                return DeviceType.MOBILE;
            }
        }

        // 判断是否为平板设备
        for (String keyword : UA_TABLET_KEYWORDS) {
            if (userAgent.contains(keyword)) {
                return DeviceType.TABLET;
            }
        }

        // Android 且不包含 mobile 关键字视为平板
        if (userAgent.contains("android") && !userAgent.contains("mobile")) {
            return DeviceType.TABLET;
        }

        // 判断是否为 PC
        for (String keyword : UA_PC_KEYWORDS) {
            if (userAgent.contains(keyword)) {
                return DeviceType.PC;
            }
        }

        return DeviceType.UNKNOWN;
    }

    /**
     * 获取设备类型（重载函数，额外传递 key）
     * 从请求参数或请求头中获取指定 key 的值，如果不存在则通过 User-Agent 判断
     *
     * @param key 参数名或头名
     * @return 设备类型枚举
     */
    public DeviceType getDeviceType(String key) {
        // 先从请求参数中获取
        String value = request.getParameter(key);
        if (value != null && !value.isEmpty()) {
            return parseDeviceType(value);
        }

        // 再从请求头中获取
        value = request.getHeader(key);
        if (value != null && !value.isEmpty()) {
            return parseDeviceType(value);
        }

        // 如果都没有，则使用默认的设备类型判断
        return getDeviceType();
    }

    /**
     * 解析字符串为设备类型枚举
     *
     * @param value 设备类型字符串
     * @return 设备类型枚举
     */
    private DeviceType parseDeviceType(String value) {
        if (value == null || value.isEmpty()) {
            return DeviceType.UNKNOWN;
        }

        String upperValue = value.toUpperCase();
        for (DeviceType type : DeviceType.values()) {
            if (type.getValue().equals(upperValue) || type.name().equals(upperValue)) {
                return type;
            }
        }

        // 兼容小写或其他常见写法
        String lowerValue = value.toLowerCase();
        if (lowerValue.contains("mobile")) {
            return DeviceType.MOBILE;
        }
        if (lowerValue.contains("tablet") || lowerValue.contains("pad")) {
            return DeviceType.TABLET;
        }
        if (lowerValue.contains("pc") || lowerValue.contains("windows") ||
                lowerValue.contains("mac") || lowerValue.contains("linux")) {
            return DeviceType.PC;
        }

        return DeviceType.UNKNOWN;
    }

    // ==================== 4. 获取设备ID (deviceId) ====================

    /**
     * 获取设备 ID
     * 优先从请求参数、请求头中获取，如果都没有则尝试从 Cookie 中获取
     *
     * @return 设备 ID，如果获取不到则返回 null
     */
    public String getDeviceId() {
        // 从请求参数中获取
        String deviceId = request.getParameter("deviceId");
        if (deviceId != null && !deviceId.isEmpty()) {
            return deviceId;
        }

        // 从请求头中获取
        deviceId = request.getHeader(HEADER_X_DEVICE_ID);
        if (deviceId != null && !deviceId.isEmpty()) {
            return deviceId;
        }

        deviceId = request.getHeader(HEADER_DEVICE_ID);
        if (deviceId != null && !deviceId.isEmpty()) {
            return deviceId;
        }

        // 从 Cookie 中获取（需要额外处理）
        // 这里简化处理，只从参数和头中获取

        return null;
    }

    /**
     * 获取设备 ID（重载函数，额外传递 key）
     * 从请求参数或请求头中获取指定 key 的值
     *
     * @param key 参数名或头名
     * @return 设备 ID 字符串，始终返回 String 类型
     */
    public String getDeviceId(String key) {
        // 先从请求参数中获取
        String value = request.getParameter(key);
        if (value != null && !value.isEmpty()) {
            return value;
        }

        // 再从请求头中获取
        value = request.getHeader(key);
        if (value != null && !value.isEmpty()) {
            return value;
        }

        return null;
    }

    // ==================== 5. 获取 User-Agent ====================

    /**
     * 获取 User-Agent
     *
     * @return User-Agent 字符串，如果获取不到则返回 "Unknown"
     */
    public String getUserAgent() {
        String userAgent = request.getHeader(HEADER_USER_AGENT);
        return userAgent != null ? userAgent : DEFAULT_UNKNOWN;
    }

    // ==================== 6. User-Agent 合法性校验 ====================

    /**
     * 校验 User-Agent 是否合法
     *
     * @return true-合法，false-不合法
     */
    public boolean isUserAgentValid() {
        String userAgent = getUserAgent();
        return isValidUserAgent(userAgent);
    }

    /**
     * 校验 User-Agent 是否合法
     *
     * @param userAgent User-Agent 字符串
     * @return true-合法，false-不合法
     */
    public static boolean isValidUserAgent(String userAgent) {
        // 1. 空值校验
        if (userAgent == null || userAgent.isEmpty() || DEFAULT_UNKNOWN.equals(userAgent)) {
            log.warn("HttpServletUtils.isValidUserAgent User-Agent为空或未知, userAgent={}", userAgent);
            return false;
        }

        // 2. 长度校验
        int length = userAgent.length();
        if (length < UA_MIN_LENGTH || length > UA_MAX_LENGTH) {
            log.warn("HttpServletUtils.isValidUserAgent User-Agent长度不合法, length={}, userAgent={}", length, userAgent);
            return false;
        }

        // 3. 黑名单校验（恶意爬虫/扫描器）
        String lowerUA = userAgent.toLowerCase();
        for (String keyword : UA_BLACKLIST_KEYWORDS) {
            if (lowerUA.contains(keyword)) {
                log.warn("HttpServletUtils.isValidUserAgent User-Agent命中黑名单, keyword={}, userAgent={}", keyword, userAgent);
                return false;
            }
        }

        // 4. 包含非法字符校验（只允许可见字符）
        for (char c : userAgent.toCharArray()) {
            if (c < 32 || c > 126) {
                log.warn("HttpServletUtils.isValidUserAgent User-Agent包含非法字符, illegalChar={}, userAgent={}", c, userAgent);
                return false;
            }
        }

        return true;
    }

    /**
     * 判断是否为搜索引擎爬虫
     *
     * @return true-是爬虫，false-不是
     */
    public boolean isSearchEngineBot() {
        String userAgent = getUserAgent();
        return isSearchEngineBot(userAgent);
    }

    /**
     * 判断是否为搜索引擎爬虫
     *
     * @param userAgent User-Agent 字符串
     * @return true-是爬虫，false-不是
     */
    public static boolean isSearchEngineBot(String userAgent) {
        if (userAgent == null || userAgent.isEmpty()) {
            return false;
        }
        String lowerUA = userAgent.toLowerCase();
        for (String keyword : UA_SEARCH_ENGINE_KEYWORDS) {
            if (lowerUA.contains(keyword)) {
                return true;
            }
        }
        return false;
    }

    /**
     * 判断是否为恶意爬虫/扫描器
     *
     * @return true-是恶意请求，false-不是
     */
    public boolean isMaliciousBot() {
        String userAgent = getUserAgent();
        return isMaliciousBot(userAgent);
    }

    /**
     * 判断是否为恶意爬虫/扫描器
     *
     * @param userAgent User-Agent 字符串
     * @return true-是恶意请求，false-不是
     */
    public static boolean isMaliciousBot(String userAgent) {
        if (userAgent == null || userAgent.isEmpty()) {
            log.warn("HttpServletUtils.isMaliciousBot User-Agent为空, userAgent={}", userAgent);
            return true;
        }
        String lowerUA = userAgent.toLowerCase();
        for (String keyword : UA_BLACKLIST_KEYWORDS) {
            if (lowerUA.contains(keyword)) {
                log.warn("HttpServletUtils.isMaliciousBot 检测到恶意爬虫, keyword={}, userAgent={}", keyword, userAgent);
                return true;
            }
        }
        return false;
    }

    // ==================== 7. IP 地址合法性校验 ====================

    /**
     * 校验 IPv4 地址是否合法
     *
     * @return true-合法，false-不合法
     */
    public boolean isIpv4Valid() {
        String ipv4 = getIpv4();
        return isValidIpv4(ipv4);
    }

    /**
     * 校验 IPv4 地址是否合法
     *
     * @param ip IPv4 地址字符串
     * @return true-合法，false-不合法
     */
    public static boolean isValidIpv4(String ip) {
        if (ip == null || ip.isEmpty()) {
            log.warn("HttpServletUtils.isValidIpv4 IPv4地址为空, ip={}", ip);
            return false;
        }
        boolean isValid = IPV4_PATTERN.matcher(ip).matches();
        if (!isValid) {
            log.warn("HttpServletUtils.isValidIpv4 IPv4地址格式非法, ip={}", ip);
        }
        return isValid;
    }

    /**
     * 校验 IPv6 地址是否合法
     *
     * @return true-合法，false-不合法
     */
    public boolean isIpv6Valid() {
        String ipv6 = getIpv6();
        return isValidIpv6(ipv6);
    }

    /**
     * 校验 IPv6 地址是否合法
     *
     * @param ip IPv6 地址字符串
     * @return true-合法，false-不合法
     */
    public static boolean isValidIpv6(String ip) {
        if (ip == null || ip.isEmpty()) {
            log.warn("HttpServletUtils.isValidIpv6 IPv6地址为空, ip={}", ip);
            return false;
        }
        boolean isValid = IPV6_PATTERN.matcher(ip).matches();
        if (!isValid) {
            log.warn("HttpServletUtils.isValidIpv6 IPv6地址格式非法, ip={}", ip);
        }
        return isValid;
    }

    /**
     * 校验 IP 地址是否合法（IPv4 或 IPv6）
     *
     * @return true-合法，false-不合法
     */
    public boolean isIpValid() {
        String ip = getClientIp();
        return isValidIp(ip);
    }

    /**
     * 校验 IP 地址是否合法（IPv4 或 IPv6）
     *
     * @param ip IP 地址字符串
     * @return true-合法，false-不合法
     */
    public static boolean isValidIp(String ip) {
        if (ip == null || ip.isEmpty()) {
            log.warn("HttpServletUtils.isValidIp IP地址为空, ip={}", ip);
            return false;
        }
        boolean isValid = isValidIpv4(ip) || isValidIpv6(ip);
        if (!isValid) {
            log.warn("HttpServletUtils.isValidIp IP地址格式非法, ip={}", ip);
        }
        return isValid;
    }

    /**
     * 校验 IP 地址是否为内网地址
     *
     * @return true-内网地址，false-公网地址
     */
    public boolean isPrivateIp() {
        String ip = getClientIp();
        return isPrivateIp(ip);
    }

    /**
     * 校验 IP 地址是否为内网地址
     *
     * @param ip IP 地址字符串
     * @return true-内网地址，false-公网地址
     */
    public static boolean isPrivateIp(String ip) {
        if (ip == null || ip.isEmpty()) {
            log.warn("HttpServletUtils.isPrivateIp IP地址为空, ip={}", ip);
            return false;
        }

        // 127.0.0.1
        if (ip.startsWith("127.")) {
            return true;
        }

        // 10.0.0.0/8
        if (ip.startsWith("10.")) {
            return true;
        }

        // 172.16.0.0/12
        if (ip.startsWith("172.")) {
            String[] parts = ip.split("\\.");
            if (parts.length == 4) {
                try {
                    int second = Integer.parseInt(parts[1]);
                    if (second >= 16 && second <= 31) {
                        return true;
                    }
                } catch (NumberFormatException e) {
                    log.warn("HttpServletUtils.isPrivateIp 解析IP段异常, ip={}, error={}", ip, e.getMessage());
                }
            }
        }

        // 192.168.0.0/16
        if (ip.startsWith("192.168.")) {
            return true;
        }

        // IPv6 内网地址
        if (ip.startsWith("fe80:") || ip.startsWith("fc") || ip.startsWith("fd")) {
            return true;
        }

        return false;
    }

    // ==================== 8. 综合校验 ====================

    /**
     * 综合校验请求信息是否合法
     *
     * @return true-全部合法，false-存在不合法项
     */
    public boolean isRequestValid() {
        // 校验设备ID
        String deviceId = getDeviceId();
        if (deviceId == null || deviceId.isEmpty()) {
            log.warn("HttpServletUtils.isRequestValid 设备ID为空, deviceId={}", deviceId);
            return false;
        }

        // 校验设备类型
        DeviceType deviceType = getDeviceType();
        if (deviceType == DeviceType.UNKNOWN) {
            log.warn("HttpServletUtils.isRequestValid 设备类型未知, deviceType={}, deviceId={}", deviceType, deviceId);
            return false;
        }

        // 校验IP
        String ip = getClientIp();
        if (!isValidIp(ip)) {
            log.warn("HttpServletUtils.isRequestValid IP地址非法, ip={}, deviceId={}", ip, deviceId);
            return false;
        }

        // 校验UserAgent
        String userAgent = getUserAgent();
        if (!isValidUserAgent(userAgent)) {
            log.warn("HttpServletUtils.isRequestValid User-Agent非法, userAgent={}, deviceId={}", userAgent, deviceId);
            return false;
        }

        return true;
    }

    // ==================== 私有辅助方法 ====================

    /**
     * 获取客户端 IP 地址
     * 依次从 X-Forwarded-For、Proxy-Client-IP、WL-Proxy-Client-IP 头中获取
     *
     * @return 客户端 IP 地址
     */
    private String getClientIp() {
        for (String header : PROXY_IP_HEADERS) {
            String ip = request.getHeader(header);
            if (ip != null && !ip.isEmpty() && !UNKNOWN_IP.equalsIgnoreCase(ip)) {
                // X-Forwarded-For 可能包含多个 IP，取第一个
                if (ip.contains(IP_SEPARATOR)) {
                    ip = ip.split(IP_SEPARATOR)[0].trim();
                }
                return ip;
            }
        }

        // 如果从代理头中获取不到，则从 RemoteAddr 中获取
        return request.getRemoteAddr();
    }

    /**
     * 获取本机 IPv4 地址（静态方法，用于辅助）
     *
     * @return 本机 IPv4 地址
     */
    public static String getLocalIpv4() {
        try {
            Enumeration<NetworkInterface> interfaces = NetworkInterface.getNetworkInterfaces();
            while (interfaces.hasMoreElements()) {
                NetworkInterface ni = interfaces.nextElement();
                Enumeration<InetAddress> addresses = ni.getInetAddresses();
                while (addresses.hasMoreElements()) {
                    InetAddress addr = addresses.nextElement();
                    if (!addr.isLoopbackAddress() && !addr.isLinkLocalAddress() &&
                            addr.getHostAddress() != null && IPV4_PATTERN.matcher(addr.getHostAddress()).matches()) {
                        return addr.getHostAddress();
                    }
                }
            }
        } catch (Exception e) {
            log.error("HttpServletUtils.getLocalIpv4 获取本机IPv4地址异常, error={}", e.getMessage(), e);
        }
        try {
            return InetAddress.getLocalHost().getHostAddress();
        } catch (UnknownHostException e) {
            log.error("HttpServletUtils.getLocalIpv4 获取本地主机地址异常, error={}", e.getMessage(), e);
            return null;
        }
    }

    /**
     * 获取本机 IPv6 地址（静态方法，用于辅助）
     *
     * @return 本机 IPv6 地址
     */
    public static String getLocalIpv6() {
        try {
            Enumeration<NetworkInterface> interfaces = NetworkInterface.getNetworkInterfaces();
            while (interfaces.hasMoreElements()) {
                NetworkInterface ni = interfaces.nextElement();
                Enumeration<InetAddress> addresses = ni.getInetAddresses();
                while (addresses.hasMoreElements()) {
                    InetAddress addr = addresses.nextElement();
                    if (!addr.isLoopbackAddress() && !addr.isLinkLocalAddress() &&
                            addr.getHostAddress() != null && addr.getHostAddress().contains(":")) {
                        return addr.getHostAddress();
                    }
                }
            }
        } catch (Exception e) {
            log.error("HttpServletUtils.getLocalIpv6 获取本机IPv6地址异常, error={}", e.getMessage(), e);
        }
        return null;
    }

    // ==================== 9. 读取请求体 ====================

    /**
     * 从 HttpServletRequest 中读取请求体，并反序列化为指定类型的对象。
     *
     * @param tClass 目标类型 Class
     * @param <T>    泛型类型
     * @return 反序列化后的对象，如果请求体为空则返回 null
     * @throws IOException 读取请求体或反序列化失败时抛出
     */
    public <T> T readRequestBody(Class<T> tClass) throws IOException {
        return readRequestBody(tClass, true);
    }

    /**
     * 从 HttpServletRequest 中读取请求体，并反序列化为指定类型的对象。
     *
     * @param tClass      目标类型 Class
     * @param checkSize   是否校验请求体大小
     * @param <T>         泛型类型
     * @return 反序列化后的对象，如果请求体为空则返回 null
     * @throws IOException 读取请求体或反序列化失败时抛出
     */
    public <T> T readRequestBody(Class<T> tClass, boolean checkSize) throws IOException {
        String body = readRequestBody();
        if (StrUtil.isEmpty(body)) {
            log.warn("HttpServletUtils.readRequestBody 请求体为空, uri={}", request.getRequestURI());
            return null;
        }

        // 校验请求体大小
        if (checkSize) {
            int bodySize = body.getBytes(StandardCharsets.UTF_8).length;
            if (bodySize > MAX_REQUEST_BODY_SIZE) {
                log.warn("HttpServletUtils.readRequestBody 请求体过大, size={}, maxSize={}, uri={}",
                        bodySize, MAX_REQUEST_BODY_SIZE, request.getRequestURI());
                return null;
            }
        }

        if (!JSONUtil.isTypeJSON(body)) {
            log.warn("HttpServletUtils.readRequestBody 非JSON格式请求体, uri={}, bodyPreview={}",
                    request.getRequestURI(), truncateBody(body));
            return null;
        }

        try {
            return JSONUtil.toBean(body, tClass);
        } catch (Exception e) {
            log.error("HttpServletUtils.readRequestBody JSON反序列化失败, uri={}, error={}",
                    request.getRequestURI(), e.getMessage(), e);
            throw new IOException("JSON反序列化失败: " + e.getMessage(), e);
        }
    }

    /**
     * 从 HttpServletRequest 中读取请求体
     *
     * @return 请求体字符串
     * @throws IOException 读取请求体失败时抛出
     */
    public String readRequestBody() throws IOException {
        if (request == null) {
            log.error("HttpServletUtils.readRequestBody HttpServletRequest对象为空");
            throw new IllegalStateException("HttpServletRequest对象为空");
        }

        try {
            String body = StreamUtils.copyToString(request.getInputStream(), StandardCharsets.UTF_8);
            log.debug("HttpServletUtils.readRequestBody 读取请求体成功, uri={}, size={}",
                    request.getRequestURI(), body.length());
            return body;
        } catch (IOException e) {
            log.error("HttpServletUtils.readRequestBody 读取请求体失败, uri={}, error={}",
                    request.getRequestURI(), e.getMessage(), e);
            throw e;
        }
    }

    /**
     * 从 HttpServletRequest 中读取请求体，失败时返回默认值
     *
     * @param defaultValue 读取失败时的默认值
     * @return 请求体字符串或默认值
     */
    public String readRequestBody(String defaultValue) {
        try {
            String body = readRequestBody();
            return StrUtil.isNotEmpty(body) ? body : defaultValue;
        } catch (IOException e) {
            log.error("HttpServletUtils.readRequestBody 读取请求体失败, 使用默认值, error={}", e.getMessage());
            return defaultValue;
        }
    }

    /**
     * 从 HttpServletRequest 中读取请求体，并反序列化为指定类型的对象，失败时返回默认值
     *
     * @param tClass       目标类型 Class
     * @param defaultValue 读取失败时的默认值
     * @param <T>          泛型类型
     * @return 反序列化后的对象或默认值
     */
    public <T> T readRequestBody(Class<T> tClass, T defaultValue) {
        return readRequestBody(tClass, defaultValue, true);
    }

    /**
     * 从 HttpServletRequest 中读取请求体，并反序列化为指定类型的对象，失败时返回默认值
     *
     * @param tClass       目标类型 Class
     * @param defaultValue 读取失败时的默认值
     * @param checkSize    是否校验请求体大小
     * @param <T>          泛型类型
     * @return 反序列化后的对象或默认值
     */
    public <T> T readRequestBody(Class<T> tClass, T defaultValue, boolean checkSize) {
        try {
            T result = readRequestBody(tClass, checkSize);
            return result != null ? result : defaultValue;
        } catch (IOException e) {
            log.error("HttpServletUtils.readRequestBody 读取请求体失败, 使用默认值, error={}", e.getMessage());
            return defaultValue;
        }
    }

    /**
     * 从 HttpServletRequest 中读取请求体，并反序列化为指定类型的对象（不校验请求体大小）
     *
     * @param tClass 目标类型 Class
     * @param <T>    泛型类型
     * @return 反序列化后的对象，如果请求体为空则返回 null
     * @throws IOException 读取请求体或反序列化失败时抛出
     */
    public <T> T readRequestBodyWithoutSizeCheck(Class<T> tClass) throws IOException {
        return readRequestBody(tClass, false);
    }

    /**
     * 从 HttpServletRequest 中读取请求体，并反序列化为指定类型的对象（不校验请求体大小），失败时返回默认值
     *
     * @param tClass       目标类型 Class
     * @param defaultValue 读取失败时的默认值
     * @param <T>          泛型类型
     * @return 反序列化后的对象或默认值
     */
    public <T> T readRequestBodyWithoutSizeCheck(Class<T> tClass, T defaultValue) {
        return readRequestBody(tClass, defaultValue, false);
    }

    /**
     * 判断请求体是否为空
     *
     * @return true-为空，false-不为空
     */
    public boolean isRequestBodyEmpty() {
        try {
            String body = readRequestBody();
            return StrUtil.isEmpty(body);
        } catch (IOException e) {
            log.error("HttpServletUtils.isRequestBodyEmpty 检查请求体失败, error={}", e.getMessage());
            return true;
        }
    }

    /**
     * 判断请求体是否为空（不读取流，仅检查内容长度）
     *
     * @return true-为空，false-不为空
     */
    public boolean isRequestBodyEmptyByLength() {
        if (request == null) {
            return true;
        }
        try {
            int contentLength = request.getContentLength();
            return contentLength <= 0;
        } catch (Exception e) {
            log.warn("HttpServletUtils.isRequestBodyEmptyByLength 获取Content-Length失败, error={}", e.getMessage());
            return true;
        }
    }

    // ==================== 10. 写出响应内容 ====================

    /**
     * 向 HttpServletResponse 写入响应体（使用 HttpStatus）。
     * <p>
     * 自动将 HttpStatus 转换为对应的状态码和描述信息，构建统一的 Result 对象返回。
     * </p>
     *
     * @param httpStatus HTTP 状态枚举
     */
    public void writeResponseBody(HttpStatus httpStatus) {
        writeResponseBody(Result.create(httpStatus.value(), httpStatus.getReasonPhrase()));
    }

    /**
     * 向 HttpServletResponse 写入响应体（自定义状态码和消息）。
     *
     * @param code    自定义状态码
     * @param message 响应消息
     */
    public void writeResponseBody(int code, String message) {
        writeResponseBody(Result.create(code, message));
    }

    /**
     * 向 HttpServletResponse 写入响应体（使用 Result 对象）。
     * <p>
     * 该方法会将 Result 对象序列化为 JSON 字符串，设置响应头为 application/json，
     * 并写入响应输出流。
     * </p>
     *
     * @param result 响应结果对象
     * @throws RuntimeException 写入响应失败时抛出（包装 IOException）
     */
    public void writeResponseBody(Result result) {
        writeResponseBody(result, HttpStatus.OK.value());
    }

    /**
     * 向 HttpServletResponse 写入响应体（使用 Result 对象，可自定义 HTTP 状态码）。
     *
     * @param result     响应结果对象
     * @param httpStatus HTTP 状态码（如 200、401、500 等）
     */
    public void writeResponseBody(Result result, int httpStatus) {
        if (response == null) {
            log.error("HttpServletUtils.writeResponseBody HttpServletResponse对象为空");
            throw new IllegalStateException("HttpServletResponse对象为空");
        }

        if (response.isCommitted()) {
            log.warn("HttpServletUtils.writeResponseBody 响应已提交，无法写入, uri={}",
                    request != null ? request.getRequestURI() : "unknown");
            return;
        }

        try {
            String json = JSONUtil.toJsonStr(result);
            response.setContentType(CONTENT_TYPE);
            response.setCharacterEncoding(CHARSET);
            response.setStatus(httpStatus);
            response.setContentLength(json.getBytes(StandardCharsets.UTF_8).length);

            response.getWriter().write(json);
            response.getWriter().flush();

            log.debug("HttpServletUtils.writeResponseBody 写入响应成功, status={}, code={}, uri={}",
                    httpStatus, result.getCode(), request != null ? request.getRequestURI() : "/");
        } catch (IOException e) {
            log.error("HttpServletUtils.writeResponseBody 写入响应失败, status={}, error={}",
                    httpStatus, e.getMessage(), e);
            throw new RuntimeException("写入响应失败", e);
        }
    }

    /**
     * 向 HttpServletResponse 写入错误响应（用于异常处理）
     *
     * @param httpStatus HTTP 状态码
     * @param message    错误消息
     */
    public void writeErrorResponse(HttpStatus httpStatus, String message) {
        writeErrorResponse(httpStatus.value(), message);
    }

    /**
     * 向 HttpServletResponse 写入错误响应（用于异常处理）
     *
     * @param code    业务状态码
     * @param message 错误消息
     */
    public void writeErrorResponse(int code, String message) {
        writeResponseBody(Result.error(code, message), HttpStatus.OK.value());
    }

    /**
     * 向 HttpServletResponse 写入成功响应
     *
     * @param data 响应数据
     * @param <T>  数据类型
     */
    public <T> void writeSuccessResponse(T data) {
        writeResponseBody(Result.success(data));
    }

    /**
     * 向 HttpServletResponse 写入成功响应（不带数据）
     */
    public void writeSuccessResponse() {
        writeResponseBody(Result.success());
    }

    /**
     * 向 HttpServletResponse 写入成功响应（自定义状态码和消息）
     *
     * @param code    业务状态码
     * @param message 成功消息
     * @param data    响应数据
     * @param <T>     数据类型
     */
    public <T> void writeSuccessResponse(int code, String message, T data) {
        writeResponseBody(Result.create(code, message, data));
    }

    // ==================== 私有辅助方法 ====================

    /**
     * 截断请求体用于日志输出
     *
     * @param body 请求体
     * @return 截断后的字符串
     */
    private String truncateBody(String body) {
        if (body == null) {
            return null;
        }
        int maxLength = 200;
        if (body.length() <= maxLength) {
            return body;
        }
        return body.substring(0, maxLength) + "...(truncated)";
    }

    /**
     * 安全获取请求属性，避免空指针
     */
    public <T> T getAttributeSafe(String key, Class<T> targetType) {
        if (key == null || targetType == null) {
            log.warn("HttpServletUtils.getAttributeSafe 参数不能为 null");
            return null;
        }

        try {
            Object value = request.getAttribute(key);
            if (value == null) {
                return null;
            }

            // 直接匹配
            if (targetType.isInstance(value)) {
                return targetType.cast(value);
            }

            // 字符串转换
            if (targetType == String.class) {
                return targetType.cast(value.toString());
            }

            // 数字类型转换
            if (Number.class.isAssignableFrom(targetType)) {
                return convertToNumber(value, targetType);
            }

            // Boolean 转换
            if (targetType == Boolean.class) {
                return targetType.cast(convertToBoolean(value));
            }

            // 枚举转换（可选）
            if (targetType.isEnum()) {
                return convertToEnum(value, targetType);
            }

            log.warn("HttpServletUtils.getAttributeSafe 不支持的类型转换: {} -> {}",
                    value.getClass().getSimpleName(), targetType.getSimpleName());
            return null;

        } catch (Exception e) {
            log.warn("HttpServletUtils.getAttributeSafe 获取属性失败, key: {}, error: {}",
                    key, e.getMessage(), e);
            return null;
        }
    }

    @SuppressWarnings("unchecked")
    private <T> T convertToNumber(Object value, Class<T> targetType) {
        Number number;
        if (value instanceof Number) {
            number = (Number) value;
        } else if (value instanceof String) {
            try {
                number = new BigDecimal((String) value);
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("无法转换为数字: " + value);
            }
        } else {
            throw new IllegalArgumentException("不支持的数字类型: " + value.getClass());
        }

        if (targetType == Integer.class || targetType == Integer.TYPE) {
            return (T) Integer.valueOf(number.intValue());
        }
        if (targetType == Long.class || targetType == Long.TYPE) {
            return (T) Long.valueOf(number.longValue());
        }
        if (targetType == Double.class || targetType == Double.TYPE) {
            return (T) Double.valueOf(number.doubleValue());
        }
        if (targetType == Float.class || targetType == Float.TYPE) {
            return (T) Float.valueOf(number.floatValue());
        }
        if (targetType == Short.class || targetType == Short.TYPE) {
            return (T) Short.valueOf(number.shortValue());
        }
        if (targetType == Byte.class || targetType == Byte.TYPE) {
            return (T) Byte.valueOf(number.byteValue());
        }
        throw new IllegalArgumentException("不支持的数字类型: " + targetType);
    }

    private boolean convertToBoolean(Object value) {
        if (value instanceof Boolean) {
            return (Boolean) value;
        }
        if (value instanceof String) {
            String str = ((String) value).toLowerCase();
            return "true".equals(str) || "1".equals(str) || "yes".equals(str);
        }
        if (value instanceof Number) {
            return ((Number) value).intValue() != 0;
        }
        throw new IllegalArgumentException("无法转换为Boolean: " + value);
    }

    @SuppressWarnings("unchecked")
    private <T> T convertToEnum(Object value, Class<T> enumType) {
        if (value instanceof String) {
            try {
                return (T) Enum.valueOf((Class<Enum>) enumType, (String) value);
            } catch (IllegalArgumentException e) {
                // 尝试按 ordinal 转换
                try {
                    int ordinal = Integer.parseInt((String) value);
                    Enum<?>[] constants = (Enum<?>[]) enumType.getEnumConstants();
                    if (ordinal >= 0 && ordinal < constants.length) {
                        return (T) constants[ordinal];
                    }
                } catch (NumberFormatException ignored) {
                    // 忽略
                }
                throw new IllegalArgumentException("无法转换为枚举: " + value);
            }
        }
        throw new IllegalArgumentException("无法转换为枚举: " + value);
    }
}
